### ISSUE TITLE
some issues compared to xterm

### ISSUE THREAD

**Issue by petersieg** [rricharz/Tek4010#15]
1st. Thanks a lot for this! Output really looks GOOD!
Some issues compared to xterm -e cu -l /dev/ttyUSB1 -s 9600
(small avrcpm usb-serial cp/m system connected)
1. line/output goes after last line from left bottom to half line right top - and continues until right bottom - than goes to left top - when pressing just return and system answers with A> prompt.
2. tek4014 also does no screen clearing, when it scrolls/should scroll.
In both cases, xterm does, what was expected:
1. scrolls after last line reached + clears screen when scrolling
--
This arduino demo does work on output side, but NOT at GIN/input mouse side at all:
https://forum.arduino.cc/index.php?topic=523751.0

best, Peter

**Comment by rricharz** [comment]
Hi, indeed what you describe is the behavior of the original hardware. It does take a bit of time to get used to it. Xterm is not a true tektronix emulator. It was written with the purpose of being able to display some tektronix data, without trying to behave like the original hardware or handling all modes. Tek 4010 emulates the original hardware, not xterm. But in fact some of the original Tektronix terminals had a switch which allowed to turn the second column off. In that case the cursor jumped back to line 1, position 1 without erasing the screen. I plan to implement that switch in a future version of tek4010.

**Comment by petersieg** [comment]
Hi. Yes, you are right. I just got the information, that the behavior is correct compared to the real hardware.
So it is 100% understandable, that you want to leave it the way it is. However, this would mean, that you cannot just connect anything, that wants just a plain, scrolling and clearing text terminal, but at the same time also wants Tek4014 graphics output at same line/terminal. That would mean, one needs a normal terminal (cu; minicom; teraterm; putty) on one line and a tek4014 on another line.
Maybe you could think of implementing another command line switch to accomodate this 'xterm' funktionality ;-)
Many thanks, Peter

**Comment by rricharz** [comment]
I will definitely not implement any scrolling. That would totally be against the idea to emulate storage tube terminals. Yes, you are right that typical computers had multiple terminals, often a teletype or similar terminal for the console, and terminals like the VT-100 for text editing. Tektronix graphics terminals were expensive and used for graphics. The screen was erased manually or under computer control.

Would a command line switch „-autoclear“ meet your needs, if it would clear the screen and jump back to line 1 if a line feed is executed on the bottom line?

**Comment by petersieg** [comment]
Hi. Yes. You are 100% right! 
But a command line switch „-autoclear“, that would clear the screen and jump back to line 1 if a line feed is executed on the bottom line, would be perfect!
Many thanks for this great piece of software!
best, Peter

**Comment by rricharz** [comment]
OK, I will add this in the next few days.

**Comment by rricharz** [comment]
The command line switch -autoClear has been added to handle this issue.

**Comment by petersieg** [comment]
Hello Rene.

 

Just downloaded, compiled an tested:

works like a charme!

 

Many thanks, Peter

 

Gesendet: Donnerstag, 20. Juni 2019 um 09:41 Uhr
Von: "Rene Richarz" <notifications@github.com>
An: rricharz/Tek4010 <Tek4010@noreply.github.com>
Cc: "Peter Sieg" <peter.sieg1@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [rricharz/Tek4010] some issues compared to xterm (#15)


The command line switch -autoClear has been added to handle this issue.
