### ISSUE TITLE
Program refuses to create a full screen windows

### ISSUE THREAD

**Issue by soviet9922** [rricharz/Tek4010#28]
Hello, have an issue trying to get a full-screen window.
Build a "custom retro terminal" like you do but I'm using a CRT screen that is 1024x768.
My idea is to run the tek4010 on full screen, when launching the emulator on x-windows (x is in 1024x768) the emulator always creates a window-sized "903 x 688" passing the parameters -full or -fullv seem to have no effect.
When the software starts shows "tek 4010 version 1.6 Screen dimensions: 1024 x 768" so the resolution seems to be recognized correctly. But the final line output in xterm before opening the new window is "Window dimensions: 903x688 Scaling: 0.220"
There's any way to force the windows to be 1024x768 ?.

Thanks!.

**Comment by rricharz** [comment]
Thanks for your input. There is indeed a problem with a screen of 1024x768. I will investigate and let you know more in a few days.

**Comment by rricharz** [comment]
The original Tektronix 4010 had coordinates of 1024 x 780 (not 768!), and the Tektronix 4014 had four times that. The code tries to make an exception for 1024x768 screens, but there might be a bug there.

I have not been able to find such a bug in the code, but I do not have a 1024x768 screen to test. What I did was add some code to make it believe that the screen was 1024x768. That worked properly. Can you please try the following and let me know:

 ./tek4010 -full -noexit cat dodekagon.plt

Do you get a full screen display with a dodekagon?

Now type ctrl-q to exit the program and close the full screen window.

Does the text window show
  Screen dimensions: 1024x768
 Window dimensions: 1024X768

If not, what does it show? Are you using a Raspberry Pi or another linux system?

If it does not work properly, would you be able to make a few changes in the code at my request to find out what's going on?
