### ISSUE TITLE
PAGE resets font size

### ISSUE THREAD

**Issue by aap** [rricharz/Tek4010#29]
According to the 4014 manual the PAGE key and the ESC+FF sequence are equivalent and should not reset the font size.
I know there is the -keepsize option, but it seems to be more of a hack to be honest. The RESET key should reset the font size, but this key doesn't seem to exist in your emulation.
EDIT: just to clarify, I suggest to get rid of the keepsize option and instead implement the RESET key.

**Comment by rricharz** [comment]
Some of the historical plot files change the font size, but most of them require font size 1 without setting it. These were probably plot files for the 4010. The - keepsize option gives you the option to run it like a 4014 with sticky smaller characters. The implementation of the RESET key would not solve the problem, because it is a key and not a character sent by the plot file.

**Comment by aap** [comment]
Hm, does the 4010 even have different character sizes? I don't think I saw that in the manual. In any case I think it should be specified somewhere that -keepsize is the option for accurate 4014 emulation. Changing the font size really doesn't make much sense if it's reset on every clear if you want to use it as a regular video terminal.

**Comment by LegalizeAdulthood** [comment]
By "font size" I assume you are talking about the `ESC 8`, `ESC 9`, `ESC :` and `ESC ;` sequences that select the number of lines and characters per line in alphanumeric mode on the 4014.

The 4010 doesn't support this feature, so when emulating the 4010, nothing should change and these ESC sequences should be ignored.  (I haven't checked the schematic to see what a 4010 would actually do, but I suspect the `ESC` would be gobbled up and the following character treated normally if it wasn't a recognized ESC sequence.  The 4010/4014 have no microprocessor and handle ESC sequence processing through a state machine implemented in discrete logic.)

**Comment by RonnySvedman** [comment]
Yup, the 4006, like the 4010 have just one text size.
