### ISSUE TITLE
ARDS mode

### ISSUE THREAD

**Issue by larsbrinkhoff** [rricharz/Tek4010#3]
Would you accept a contribution to add an ARDS mode?

http://www.bitsavers.org/pdf/computerDisplaysInc/RM86802_ARDS_RefMan_Dec68.pdf

**Comment by larsbrinkhoff** [comment]
Timing information:
- Input normally operates at 1200 baud.
- Characters take 1-2 milliseconds to draw.
- Vectors take 1-8 milliseconds.

**Comment by rricharz** [comment]
Development started.

**Comment by larsbrinkhoff** [comment]
Screenshot, from page 28 on http://www.bitsavers.org/pdf/mitre/ESD_Technical_Reports/ESD-TR-69-358_Microprogramming_Facility_Nov69.pdf

![ards1](https://user-images.githubusercontent.com/775050/56128875-23598500-5f81-11e9-873b-a2fedc57258d.png)

**Comment by rricharz** [comment]
We need a list of references, especially for the less known ARDS. This document should definitely be there.
references.txt?

**Comment by rricharz** [comment]
Do you mean this?
![2019-04-15-141429_1024x780_scrot](https://user-images.githubusercontent.com/18350635/56131974-2a849100-5f89-11e9-9bed-9554bb96d5ac.png)

I have the quick and dirty little c test program to make it using tek codes. Would be easy for you to modify. If you want it I will push it.

**Comment by larsbrinkhoff** [comment]
Nice!  I was hoping to also extract some information about the text.

**Comment by rricharz** [comment]
Lars,
I am ready now to release the current version of tek4010 as version 1.2.5. All reported bugs have been fixed, and it works well on all kind of systems. The storage tube handler and the tek4010 decoder seem to be quite stable now. There are 3 options:
1. I add skaling to your current version of ards.c. Appears to be very easy.
2. I comment out the -ARDS option for now.
3. A wait for a pull request from your side.
Which option do you prefer?

**Comment by larsbrinkhoff** [comment]
> 1 I add skaling to your current version of ards.c. Appears to be very easy. 

This sounds good to me.  I'm on holiday now, which means family time and
not much time for hobbies.

**Comment by rricharz** [comment]
Mouse support not yet implemented

**Comment by larsbrinkhoff** [comment]
I'm not aware of anything in ITS that accepts mouse commands from an ARDS.

There's probably some programs for Multics that can write ARDS output.  Maybe there's the best place to also look for input capabilities.

I wonder if there are any ARDS programs for CTSS.  @rcornwell, do you know?

Outside MIT, use of ARDS terminals were probably unusual, and preserved software even more so uncommon.

**Comment by larsbrinkhoff** [comment]
I asked a Multics person about ARDS and got this:
> Not aware of any ARDS and nothing that uses the mouse.  All the Multics stuff used the Graphics system, and ARDS was just one output driverof many - it seems most common was plotters and Tek terminals.

**Comment by larsbrinkhoff** [comment]
If you like, I think this issue can be closed now.

**Comment by rricharz** [comment]
I‘m closing this issue for now. There is more than enough historic evidence that the ARDS did support both a mouse built by CDI and a joystick in 1968, see https://github.com/PDP-10/its/issues/821, but we were unable to find any historic code supporting it.

**Comment by larsbrinkhoff** [comment]
Here's another screenshot.  This is from page 75 of [Project MAC Progress Report V, 1967-1968](https://apps.dtic.mil/dtic/tr/fulltext/u2/687770.pdf).

![ards-globe](https://user-images.githubusercontent.com/775050/57191792-b440d200-6f29-11e9-8f25-456d335bf875.png)

**Comment by larsbrinkhoff** [comment]
In particular note the character set.  It seems to be consistent with the previous screen shot.

Are these all the 94 printables?  I think there's a "logical not" ¬ symbol, and that's probably the modern ~ ASCII character.

![ards-chars](https://user-images.githubusercontent.com/775050/57191901-f1599400-6f2a-11e9-9e98-5b4ab6005111.png)

**Comment by rricharz** [comment]
ASCII codes prior to 1968 are a very complex story. See for example
https://worldpowersystems.com/archives/codes/
Do you have any ARDS plot files requiring fixing the character set?

**Comment by rricharz** [comment]
Maybe this is more helpful https://www.aivosto.com/articles/charsets-7bit.html#body

**Comment by larsbrinkhoff** [comment]
No, I have nothing that requires a fix.

I'm thinking about maybe, some time in the distant future, make a change to draw the characters so they're as close as possible to the above.  But it's low priority.

**Comment by larsbrinkhoff** [comment]
Better screenshots?  Two pages.

http://www.bitsavers.org/magazines/Computer_Design/196804.pdf#page=84

**Comment by rricharz** [comment]
Very interesting
