### ISSUE TITLE
Remove apltest binary from git repo and add to gitignore?

### ISSUE THREAD

**Issue by tvrusso** [rricharz/Tek4010#34]
I build Tek4010 on a non-Raspberry pi, non-Linux system, and test it out using a freshly built apltest.  To do this I have to maintain a local branch with some tiny modifications that remove some minor linuxisms, and keep that branch rebased off of master to stay up to date.

The presence of an RPi binary for apltest in the repo makes using git a little difficult, just as the older presence of the tek4010 binary used to.

It would be great if the apltest binary could be removed from the repo and apl/apltest added to .gitignore just as was done recently for the tek4010 binary.

**Comment by tvrusso** [comment]
In this regard, this issue is mostly a duplicate of #21, but I think #21 has already in fact been addressed by commit 8e946f34

**Comment by rricharz** [comment]
Binaries removed in latest version

**Comment by tvrusso** [comment]
The binary for apltest is still in the repo.  Only the tek4010 binary was removed.
![image](https://github.com/rricharz/Tek4010/assets/10872812/3a91647b-75d0-4038-817c-96cee52ef0ca)

And only some binaries are in .gitignore.

```
# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex
tek4010
previous_version/tek4010
```

**Comment by tvrusso** [comment]
In fact, there have been no commits in the apl directory for 5 years.

**Comment by rricharz** [comment]
Sorry, forgot the push: It should be ok right now.
