### ISSUE TITLE
GNU check target

### ISSUE THREAD

**Issue by polluks** [rricharz/Tek4010#43]
I would like to use `make check` for quick feedback.
Something like
```makefile
check: tek4010
        make -C tektests

**Comment by rricharz** [comment]
Sorry, I don‘t understand what you want to achieve from a user point of view.

**Comment by polluks** [comment]
"[check] performs self-tests (if any). The user must build the program before running the tests, but need not install the program; you should write the self-tests so that they work when the program is built but not installed."
https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html
