### ISSUE TITLE
Installation instructions for MacOS

### ISSUE THREAD

**Issue by polluks** [rricharz/Tek4010#52]
You have to patch the BSD sed call somehow:
`"$a": command a expects \ followed by text`
see https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

**Comment by polluks** [comment]
Duplicate of #45

**Comment by rricharz** [comment]
It would be nice if you could provide installation instruction for MacOS. I could check these on my Mac and add them to the manual.

**Comment by rricharz** [comment]
Experimental installation instructions for MacOS have been added.

**Comment by rricharz** [comment]
Fixed
