### ISSUE TITLE
Display Color Adjustments

### ISSUE THREAD

**Issue by hanyazou** [rricharz/Tek4010#53]
Thank you for developing and sharing your software; I find its nostalgic display quite appealing.

I am interested in adjusting the display to more closely resemble the Tektronix 4010 videos on YouTube, particularly by reducing the saturation slightly, as the video appears less saturated. (It might due to filming effects?)

https://www.youtube.com/watch?v=2SbCIP1m6hs
https://www.youtube.com/watch?v=IztxeoHhoyM

<img width="40%" alt="20240601-204541-82097" src="https://github.com/rricharz/Tek4010/assets/493387/15ee382a-dc86-498b-ab12-ee751164e3a7">
<img width="44%" alt="20240601-204541-82113" src="https://github.com/rricharz/Tek4010/assets/493387/89052b1a-b98f-4caf-b279-c2550a697f81">

Upon reviewing the change logs, I noticed you had meticulously adjusted the settings in tube.c around 2019. Therefore, I wanted to consult with you on the visual appearance before moving forward with a pull request.

Attached below are images for comparison: the left shows the current display, and the right is the modified version with intentionally exaggerated reduced saturation for clearer visibility. Which version do you prefer?

 if opinions vary, I could implement a configuration mechanism allowing users to adjust these settings themselves. What are your thoughts on this approach?

<img width="46%" alt="Screenshot 2024-06-05 at 21 23 22" src="https://github.com/rricharz/Tek4010/assets/493387/edd4cf83-6c69-41e8-94b5-36fac66efc2e">
<img width="40%" alt="Screenshot 2024-06-05 at 21 14 35" src="https://github.com/rricharz/Tek4010/assets/493387/d3c875ad-bfde-488e-85df-f2cab6d94b25">
<img width="98%" alt="Screenshot 2024-06-05 at 21 11 01" src="https://github.com/rricharz/Tek4010/assets/493387/67dd0994-cb97-4e6a-be38-0a78b05cff2c">

**Comment by rricharz** [comment]
The actual appearance depends a lot on the white balance and brightness of the camera, and on the color quality of the computer display. Also, age and sharpness adjustments of the 4010 display are very relevant.

I have tested this on quite a number of displays, and results vary substantially. There are also differences in the many YouTube videos. But I agree that the bright spot should be more white than green.

Currently the only adjustment is the brightness of the green drawing (0.7) and of the bright spot (1.0), which were adjusted based on input from a number of users. If you give me the RGB values of the drawing and the bright spot that you prefer I will test these and decide how to proceed.

**Comment by hanyazou** [comment]
I have checked the actual RGB values.
They are shown below.

This diagram is illustrating my interpretation of the intensity and set_source_rgb() RGB values as defined in tube.c.
For simplicity, I have excluded the inclusion of BLACK_INTENSITY in the drawPoint() calculations within this diagram.
<img width="98%" alt="Screenshot 2024-06-09 at 10 53 35" src="https://github.com/rricharz/Tek4010/assets/493387/4dc0bc54-1df8-4562-8f96-dbcda38f196a">


I have updated tube.c to enhance the overall saturation by 20% and conducted a visual comparison of the images.
You can review the modifications here:
https://github.com/hanyazou/Tek4010/commit/bbc5cc7485d8ba6aa7fd232d7c014cd5a6a721af

If a 20% increase in saturation seems excessive, would a more moderate adjustment, perhaps between 10% and 15%, or providing users the ability to set their preferred levels, be a more acceptable solution?

<img width="2045" alt="Screenshot 2024-06-09 at 10 23 25" src="https://github.com/rricharz/Tek4010/assets/493387/db9ba050-6d41-450a-a51e-4151dcdfdf2b">
<img width="2047" alt="Screenshot 2024-06-09 at 10 21 51" src="https://github.com/rricharz/Tek4010/assets/493387/f0e9c263-a6f9-4801-a75c-c7affdfc955b">
<img width="2047" alt="Screenshot 2024-06-09 at 10 18 15" src="https://github.com/rricharz/Tek4010/assets/493387/4eebe5c4-b967-4789-972c-382b2c95ae2e">

vectors
<img width="721" alt="4" src="https://github.com/rricharz/Tek4010/assets/493387/ba1561fe-a817-4287-bbbb-bf1a8ec7f2f5">

<img width="270" alt="Screenshot 2024-06-09 at 11 37 51" src="https://github.com/rricharz/Tek4010/assets/493387/7ef4b16a-ad16-4edd-a315-b0510644fe68">
<img width="270" alt="Screenshot 2024-06-09 at 11 38 57" src="https://github.com/rricharz/Tek4010/assets/493387/b4a49cee-7a90-48af-8f59-e25de0940c15">


<img width="270" alt="Screenshot 2024-06-09 at 11 40 06" src="https://github.com/rricharz/Tek4010/assets/493387/b9663750-d828-448b-836a-9a5e3240b552">
<img width="270" alt="Screenshot 2024-06-09 at 11 40 33" src="https://github.com/rricharz/Tek4010/assets/493387/8dae4f82-a004-4f42-9862-e473ad2d41e9">

characters
<img width="1797" alt="3" src="https://github.com/rricharz/Tek4010/assets/493387/8fa47564-2c1c-4d6a-80a6-ab171e5f3173">

<img width="270" alt="Screenshot 2024-06-09 at 11 44 20" src="https://github.com/rricharz/Tek4010/assets/493387/4de166c7-174c-4cd6-b117-6ff08bd0bde3">
<img width="270" alt="Screenshot 2024-06-09 at 11 44 46" src="https://github.com/rricharz/Tek4010/assets/493387/fcd818bd-c2f2-411a-84f5-745299a6699a">

<img width="270" alt="Screenshot 2024-06-09 at 11 43 07" src="https://github.com/rricharz/Tek4010/assets/493387/731b8d46-94f3-446e-aa44-f53faf1bd164">
<img width="270" alt="Screenshot 2024-06-09 at 11 43 41" src="https://github.com/rricharz/Tek4010/assets/493387/69a4ecd3-d542-45c4-9110-3ce559d9da54">

points
<img width="640" alt="2" src="https://github.com/rricharz/Tek4010/assets/493387/e1c0fb55-f66a-402d-a4a7-312304d8c56f">

<img width="270" alt="Screenshot 2024-06-09 at 11 41 00" src="https://github.com/rricharz/Tek4010/assets/493387/40b37dc8-87df-49ed-88e1-7a78649d9ca8">
<img width="270" alt="Screenshot 2024-06-09 at 11 41 29" src="https://github.com/rricharz/Tek4010/assets/493387/70758beb-d2f0-41df-98e5-e1cd2383a527">

faded bright spot

<img width="270" alt="Screenshot 2024-06-09 at 11 42 03" src="https://github.com/rricharz/Tek4010/assets/493387/e5d03359-f765-477f-a7b4-ee0b01d8e4d5">
<img width="270" alt="Screenshot 2024-06-09 at 11 42 27" src="https://github.com/rricharz/Tek4010/assets/493387/bb1e9b82-ecba-4566-95d3-53b4df99bd1a">

Prior to this comparison, I calibrated my monitor to ensure accuracy.
According to the calibration, my monitor covers the entire sRGB color gamut, thus we can assume the RGB values displayed are accurate.

<img width="48%" alt="Screenshot 2024-06-09 at 11 50 21" src="https://github.com/rricharz/Tek4010/assets/493387/9f6b2080-155a-4d06-a92a-e38a4d5ee15c">

**Comment by hanyazou** [comment]
By the way, the saturation is higher than expected when drawing text strings at normal brightness.
I could not figure out why the saturation was higher in the program.

<img width="270" alt="Screenshot 2024-06-09 at 11 40 06" src="https://github.com/rricharz/Tek4010/assets/493387/b9663750-d828-448b-836a-9a5e3240b552">

<img width="270" alt="Screenshot 2024-06-09 at 11 43 07" src="https://github.com/rricharz/Tek4010/assets/493387/731b8d46-94f3-446e-aa44-f53faf1bd164">

```
// draw the character                                                                                                                                                                                                                                                         
cairo_set_source_rgb(cr, 0, BLACK_INTENSITY + ((NORMAL_INTENSITY - BLACK_INTENSITY) * intensity) / 100, 0);
cairo_move_to(cr, tube_x0, windowHeight - tube_y0 + currentCharacterOffset);
cairo_show_text(cr, s);
```

**Comment by rricharz** [comment]
Please provide a pull request with your changes.

**Comment by hanyazou** [comment]
@rricharz 

In my modification branch, I also fix a bug (I thought it is a bug).
Please look at this:
https://github.com/hanyazou/Tek4010/commit/d3037d36b4361934769bbe551f81554a8d9ced79

Can I include this change in the pull request?
If you are not sure, I will remove this change and create new branch for a pull request.

**Comment by rricharz** [comment]
Yes, this is indeed a bug. Go ahead with the pull request.
