### ISSUE TITLE
MacOS (Macintosh): Font not working

### ISSUE THREAD

**Issue by rricharz** [rricharz/Tek4010#55]
The font used to display text is not monospace. A proper font needs to be installed or selected

**Comment by hanyazou** [comment]
Andale Mono looks nice on my Mac, though I'm not sure if this font came with macOS or if I downloaded it separately.

```
- #define STANDARD_FONT "Monospace"
+ #define STANDARD_FONT "Andale Mono"
```

<img width="1314" alt="Screenshot 2024-06-09 at 15 50 45" src="https://github.com/rricharz/Tek4010/assets/493387/225c6137-138c-4f6e-ae7c-48635c867658">

**Comment by hanyazou** [comment]
According to the wikipedia the font data is bundled with macOS.

https://en.wikipedia.org/wiki/Andal%C3%A9_Mono

**Comment by rricharz** [comment]
Just found the bug. "monospace" instead of "Monospace" used default font on Mac.
