### ISSUE TITLE
Adding Bloom Effects

### ISSUE THREAD

**Issue by hanyazou** [rricharz/Tek4010#61]
Inspired by online movies, such as the "Tektronix 4052 Vector Graphics Computer - PLOT10 Demo" on YouTube (https://www.youtube.com/watch?v=2SbCIP1m6hs), I've attempted to add bloom effects to the Tek4010 emulation. While it's challenging to replicate the exact look, these additions help approximate the visual style of the video.

Since Cairo does not support these kinds of effects directly, I've achieved blur, glow and ghost effects through overlay techniques. This approach does consume some processing power and will not be used when the -fast option is specified.
You can review the implementation here: https://github.com/hanyazou/Tek4010/pull/3

Here is a comparison between the video and the corresponding screenshot of the modified Tek4010. The images on the left are from the video, and the images on the right are of the Tek4010.
Also, there is a movie of tested on my Mac: https://youtu.be/2-p46EGfoUk

I believe these effects enhance the emulation, but I would love to hear your thoughts. Do you think these are suitable additions?

Looking forward to your feedback.

<img width="53%" alt="Screenshot 2024-06-08 at 8 08 01" src="https://github.com/rricharz/Tek4010/assets/493387/67310160-9507-4478-9fae-539f90558962">
<img width="45.3%" alt="Screenshot 2024-06-15 at 13 40 49" src="https://github.com/rricharz/Tek4010/assets/493387/db1ceffc-2d0c-410b-b8b5-5225968aa2dd">

<img width="48.3%" alt="Screenshot 2024-06-08 at 6 47 46" src="https://github.com/rricharz/Tek4010/assets/493387/65ce7585-4d3a-4542-8ac3-70fa2485ca93">
<img width="48%" alt="Screenshot 2024-06-15 at 13 41 28" src="https://github.com/rricharz/Tek4010/assets/493387/394202d9-4fcb-4132-84c0-66513326abf6">

<img width="51%" alt="Screenshot 2024-06-08 at 8 15 56" src="https://github.com/rricharz/Tek4010/assets/493387/f3697e4a-d969-4f49-b3d7-7b8499a61535">
<img width="47%" alt="Screenshot 2024-06-15 at 13 42 53" src="https://github.com/rricharz/Tek4010/assets/493387/98591376-576c-4e8e-9021-84d9de5dd044">

<img width="50%" alt="Screenshot 2024-06-08 at 6 48 14" src="https://github.com/rricharz/Tek4010/assets/493387/7596fa7a-09f0-4cc9-8002-e04cd9d550d5">
<img width="47.5%" alt="Screenshot 2024-06-15 at 13 45 20" src="https://github.com/rricharz/Tek4010/assets/493387/d6013fe8-ffb4-4889-bbb1-e6e61ec724a6">

**Comment by rricharz** [comment]
I will look at your interesting proposal in a few weeks.

**Comment by rricharz** [comment]
I think these enhancements are very interesting, but are not worth the additional processing power used. I had part of it implemented in earlier versions of tek4010, but took it out later.

**Comment by hanyazou** [comment]
@rricharz 

Instead of forking the project, could we add this feature through runtime options or build options?
